// === TTS Initialization Script ===
const processedElements = new WeakSet();
const processedGroups = new WeakSet();

 const phrases = [
        "Vascular Intervention",
        "Coronary",
        "Congenital Heart",
        "Heart Valves",
        "Structural Heart",
        "Peripheral Vascular",
        "Vascular Intervention",
        "Generic",
        "Access Sheath",
        "Angiographic Imaging",
        "Angioplasty",
        "Anticoagulation Therapy",
        "Arterial Access",
        "Arterial Occlusion",
        "Atherosclerosis",
        "Atrial Septal Defect",
        "Balloon Deflation",
        "Balloon Inflation",
        "Cardiac Catheterization",
        "Cardiovascular Devices",
        "Catheterization",
        "Chronic Total Occlusion",
        "Clinical Trials",
        "Coarctation of the Aorta",
        "Congenital Heart Defects",
        "Congenital Heart Disease",
        "Coronary Angiography",
        "Coronary Artery Disease",
        "Coronary Intervention",
        "Coronary Revascularization",
        "Device Maintenance",
        "Device Performance",
        "Device Selection Criteria",
        "Device Sterilization",
        "Embolization",
        "Endarterectomy",
        "Endovenous Ablation",
        "Endovenous Laser Therapy",
        "Fractional Flow Reserve",
        "Guide Catheter",
        "Guidewire",
        "Hemodynamic Monitoring",
        "Hemodynamic Support",
        "Infection Prevention",
        "Intra Aortic Balloon Pump",
        "Intracoronary Shunt",
        "Intraoperative Imaging",
        "Intravascular Ultrasound",
        "Optical Coherence Tomography",
        "Patent Foramen Ovale",
        "Patient Outcomes",
        "Pericardial Patch",
        "Peripheral Arterial Disease",
        "Peripheral Interventions",
        "Peripheral Vascular Intervention",
        "Postoperative Monitoring",
        "Pressure Monitoring",
        "Pressure Wire",
        "Pulmonary Valve Stenosis",
        "Radiofrequency Ablation",
        "Recovery Protocols",
        "Reintervention",
        "Septal Occluder",
        "Surgical Innovation",
        "Surgical Mesh",
        "Surgical Technique",
        "Thrombectomy",
        "Vascular Access",
        "Vascular Closure Device",
        "Vascular GraP",
        "Vascular Health",
        "Vascular Intervention",
        "Vascular Reconstruction",
        "Venous Access",
        "Venous Insufficiency",
        "Ventricular Septal Defect",
        "Vascular Intervention",
        "Coronary",
        "Coronary Artery Disease",
        "Acute Coronary Syndrome",
        "Angiographic Imaging",
        "Angiographic Result",
        "Angiographic Success",
        "Angioplasty Balloon",
        "Antithrombotic Therapy",
        "Atherectomy",
        "Atherosclerosis",
        "Balloon Angioplasty",
        "Balloon Catheter",
        "Balloon Catheter ShaP",
        "Balloon Compliance",
        "Balloon Crossing Profile",
        "Balloon Deflation",
        "Balloon Diameter",
        "Balloon Dilatation",
        "Balloon Inflation",
        "Balloon Length",
        "Balloon Profile",
        "Balloon Rupture",
        "Balloon Trackability",
        "Bare Metal Stent",
        "Bioabsorbable Scaffold",
        "Biodegradable Polymer",
        "Calcified Lesion",
        "Catheter Based Therapy",
        "Chronic Total Occlusion",
        "Coronary Artery",
        "Coronary Artery Bypass GraPing",
        "Coronary Artery Spasm",
        "Coronary Flow Reserve",
        "Coronary Revascularization",
        "Distal Protection Device",
        "Drug Coated Balloon",
        "Drug Eluting Stent",
        "Dual Antiplatelet Therapy",
        "Dual Lumen Catheter",
        "Edge Dissection",
        "Elective PCI",
        "Endothelialization",
        "Endovascular Procedure",
        "Femoral Access",
        "Fractional Flow Reserve",
        "Guide Catheter",
        "Guide Catheter Backup",
        "Guidewire",
        "In Stent Restenosis",
        "Intravascular Ultrasound",
        "Ischemia",
        "Kissing Balloon Technique",
        "Lesion Coverage",
        "Lesion Morphology",
        "Lesion Preparation",
        "Metallic Scaffold",
        "Myocardial Infarction",
        "Non Compliant Balloon",
        "Optical Coherence Tomography",
        "Over the Wire System",
        "Percutaneous Coronary Intervention",
        "Percutaneous Transluminal Coronary Angioplasty",
        "Plaque Burden",
        "Plaque Debulking",
        "Plaque Eccentricity",
        "Plaque Modification",
        "Plaque Rupture",
        "Post Dilatation",
        "Pre Dilatation",
        "Pressure Wire",
        "Primary PCI",
        "Procedural Success",
        "Proximal Optimization Technique",
        "Radial Access",
        "Rapid Exchange System",
        "Rescue PCI",
        "Restenosis",
        "Scaffold",
        "Scaffold Resorption",
        "Semi Compliant Balloon",
        "Side Branch Protection",
        "Stent",
        "Stent Apposition",
        "Stent Coating",
        "Stent Coverage",
        "Stent Deployment",
        "Stent Diameter",
        "Stent Expansion",
        "Stent Fracture",
        "Stent Length",
        "Stent Placement",
        "Stent PlaXorm",
        "Stent Retraction",
        "Stent Scaffold",
        "Stent Struts",
        "Stent Thrombosis",
        "Stent Visibility",
        "Thrombectomy",
        "Thrombosis",
        "Vascular Lumen",
        "Wire Bias",
        "Vascular Intervention",
        "Congenital Heart",
        "Amplatzer Device",
        "Aneurysm",
        "Atrial Septal Defect",
        "Atrial Septum",
        "Atrial Septum Anatomy",
        "Balloon Dilatation",
        "Balloon Assisted Technique",
        "Balloon Tipped Catheter",
        "Cardiac Anatomy",
        "Cardiac Apex",
        "Cardiac Catheterization",
        "Cardiac Chambers",
        "Cardiac Defect",
        "Cardiac Imaging",
        "Cardiac Output",
        "Cardiac Rhythm",
        "Cardiopulmonary Bypass",
        "Cardiovascular Anatomy",
        "Cardiovascular Device",
        "Closure Device",
        "Congenital Defect",
        "Congenital Heart Disease",
        "Delivery Catheter",
        "Device Closure",
        "Device Compatibility",
        "Device Confirmation",
        "Device Deployment",
        "Device Deployment Accuracy",
        "Device Deployment Handle",
        "Device Erosion",
        "Device Fracture",
        "Device Implantation",
        "Device Integrity",
        "Device Lifespan",
        "Device Longevity",
        "Device Manufacturer",
        "Device Migration",
        "Device Orientation",
        "Device Oversizing",
        "Device Positioning",
        "Device Recapture",
        "Device Release Mechanism",
        "Device Repositioning",
        "Device Retention",
        "Device Retrieval",
        "Device Safety",
        "Device Sizing",
        "Device Under sizing",
        "Device Visibility",
        "Echocardiography",
        "Embolization",
        "Endocardial Surface",
        "Endovascular Access",
        "Endovascular Occlusion",
        "Endovascular Procedure",
        "Endovascular Technique",
        "Femoral Vein",
        "Fluoroscopy",
        "Guidewire",
        "Heart Murmur",
        "Heart Valve",
        "Hemodynamic Stability",
        "Implant Procedure",
        "Interatrial Septum",
        "Interventional Cardiology",
        "Intracardiac Echocardiography",
        "Intraventricular Septum",
        "Jugular Vein",
        "LeP Atrium",
        "LeP Ventricle",
        "Mitral Valve",
        "Occluder",
        "Paravalvular Leak",
        "Patent Foramen Ovale",
        "Percutaneous Approach",
        "Percutaneous Occlusion",
        "Post-Procedure Monitoring",
        "Pulmonary Hypertension",
        "Pulmonary Veins",
        "Residual Defect",
        "Residual Shunt",
        "Right Atrium",
        "Right Ventricle",
        "Septal Aneurysm",
        "Septal Edge",
        "Septal Occluder",
        "Septal Patch",
        "Septal Wall",
        "Septum Primum",
        "Septum Secundum",
        "Shunt",
        "Stent",
        "Stent Delivery System",
        "Thrombosis",
        "Transcatheter Device",
        "Transesophageal Echocardiogram",
        "Tricuspid Valve",
        "Vascular Access",
        "Vascular Sheath",
        "Ventricular Septal Defect",
        "Vascular Intervention",
        "Heart Valves",
        "Angiography",
        "Annular Size",
        "Annulus",
        "Anticoagulation Therapy",
        "Aortic Regurgitation",
        "Aortic Root",
        "Aortic Root Enlargement",
        "Aortic Stenosis",
        "Aortic Valve",
        "Atrial Fibrillation",
        "Balloon Aortic Valvuloplasty",
        "Balloon Expandable Valve",
        "Balloon Tipped Catheter",
        "Bioprosthetic Valve",
        "Cardiac Catheterization",
        "Cardiac Conduction System",
        "Cardiac Output",
        "Cardiac Rehab",
        "Cardiopulmonary Bypass",
        "Cardiothoracic Surgeon",
        "Cardiovascular Surgery",
        "Conduction Abnormality",
        "Coronary Ostia",
        "Degenerative Valve Disease",
        "Delivery Catheter",
        "Device Recapture",
        "Device Retrieval",
        "Device Sizing",
        "Echocardiography",
        "Endocarditis",
        "Endovascular Procedure",
        "Endovascular Stenting",
        "Femoral Access",
        "Fluoroscopy",
        "Heart Valve Repair",
        "Heart Valve Replacement",
        "Hemodynamics",
        "Hybrid Operating Room",
        "Interventional Cardiology",
        "Intraoperative Imaging",
        "Leaflet Coaptation",
        "LeP Ventricle",
        "LeP Ventricular OuXlow Tract",
        "Mechanical Valve",
        "Mitral Regurgitation",
        "Mitral Valve",
        "Mitral Valve Prolapse",
        "Pacemaker Lead",
        "Paravalvular Leak",
        "Paravalvular Regurgitation",
        "Percutaneous Valve Replacement",
        "Post Dilatation",
        "Postoperative Monitoring",
        "Pre Dilatation",
        "Prosthetic Valve",
        "Pulmonary Hypertension",
        "Pulmonary Valve",
        "Right Ventricle",
        "Right Ventricular OuXlow Tract",
        "Self Expanding Valve",
        "Stenotic Valve",
        "Structural Heart Disease",
        "Structural Valve Deterioration",
        "Subclavian Access",
        "Surgical Aortic Valve Replacement",
        "Surgical Valve Replacement",
        "Tissue Valve",
        "Transapical Access",
        "Transcatheter Aortic Valve Replacement",
        "Transesophageal Echocardiogram",
        "Tricuspid Valve",
        "Valve Anchoring",
        "Valve Annuloplasty",
        "Valve Calcification",
        "Valve Commissure",
        "Valve Competence",
        "Valve Coronary Alignment",
        "Valve Crimping",
        "Valve Degeneration",
        "Valve Deployment",
        "Valve Durability",
        "Valve Durability Testing",
        "Valve Endurance",
        "Valve Expansion",
        "Valve Gradient",
        "Valve Hemodynamic Performance",
        "Valve Hemodynamics",
        "Valve Implantation",
        "Valve Implantation Technique",
        "Valve Leaflet",
        "Valve Migration",
        "Valve Oversizing",
        "Valve Positioning",
        "Valve Prosthesis",
        "Valve Remodeling",
        "Valve Stent Frame",
        "Valve Under sizing",
        "Valve in Valve Procedure",
        "Vascular Access",
        "Ventricular Septal Defect",
        "Structural Heart",
        "+/- Knob",
        "A/P Rotation Knob",
        "Anti-slip Bristles",
        "Atraumatic SoP Tip",
        "Clip Sizes (SR",
        "SW",
        "LR",
        "LW)",
        "Clip-Lock Lever",
        "Deployment Pin/Knob",
        "Dilator",
        "Flush Port",
        "Grasper Lever",
        "Hemostatic Valve",
        "Hydrophilic Coating",
        "MDS Console",
        "Myclip",
        "MyClip Delivery System (MDS)",
        "MyClip Guide Catheter (MGC)",
        "MyClip TEER System",
        "NiTi Graspers",
        "Polyester Fabric Cover",
        "Radiopaque Ring",
        "Radiopaque Tip",
        "Rotary Wheel",
        "Torque Box",
        "Vascular Intervention",
        "Peripheral Vascular",
        "Acute Limb Ischemia",
        "Angioplasty",
        "Aortic Aneurysm",
        "Atherectomy",
        "Atherectomy Device",
        "Balloon Angioplasty",
        "Balloon Catheter",
        "Balloon Compliance",
        "Balloon Compliance Chart",
        "Balloon Deflation",
        "Balloon Diameter",
        "Balloon Dilatation",
        "Balloon Inflation",
        "Balloon Length",
        "Balloon Rupture",
        "Bare Metal Stent",
        "Chronic Total Occlusion",
        "Chronic Venous Disease",
        "Claudication",
        "Coil Embolization",
        "Computed Tomography Angiography",
        "Contrast Angiography",
        "Covered Stent",
        "Critical Limb Ischemia",
        "Crossing Catheter",
        "Directional Atherectomy",
        "Drug Coated Balloon",
        "Drug Eluting Stent",
        "Duplex Ultrasound",
        "Embolectomy",
        "Embolic Agent",
        "Embolic Protection Device",
        "Embolization",
        "Embolization Coil Deployment",
        "Embolization Procedure",
        "Endoleak",
        "Endovascular Aneurysm Repair",
        "Endovascular Procedure",
        "Endovascular Therapy",
        "Femoral Artery",
        "Flow Diverter",
        "Guide Catheter",
        "Guidewire",
        "Iliac Artery",
        "Inferior Vena Cava Filter",
        "Intravascular Ultrasound",
        "Laser Atherectomy",
        "Liquid Embolic",
        "Magnetic Resonance Angiography",
        "Microcatheter",
        "Non Compliant Balloon",
        "Over the Wire System",
        "Percutaneous Access",
        "Percutaneous Transluminal Angioplasty",
        "Peripheral Artery Disease",
        "Peripheral Balloon",
        "Peripheral Stent",
        "Peripheral Vascular Disease",
        "Plaque Debulking",
        "Popliteal Artery",
        "Radial Artery",
        "Rapid Exchange System",
        "Restenosis",
        "Rotational Atherectomy",
        "Saphenous Vein",
        "Semi Compliant Balloon",
        "Stent Apposition",
        "Stent Deployment",
        "Stent Diameter",
        "Stent Endothelialization",
        "Stent Expansion",
        "Stent Fracture",
        "Stent GraP",
        "Stent Length",
        "Stent Migration",
        "Stent Placement",
        "Stent Radial Force",
        "Stent Restenosis",
        "Stent Visibility",
        "Superficial Femoral Artery",
        "Thrombectomy",
        "Thrombosis",
        "Tibial Artery",
        "Varicose Veins",
        "Vascular Access",
        "Vascular Anatomy",
        "Vascular Aneurysm",
        "Vascular Closure Device",
        "Vascular Coil",
        "Vascular Flow",
        "Vascular Guidewire",
        "Vascular Imaging",
        "Vascular Lumen",
        "Vascular Malformation",
        "Vascular Occlusion",
        "Vascular Remodeling",
        "Vascular Sheath",
        "Vascular Stenosis",
        "Venous Insufficiency",
        "Vessel Patency",
        "Cardiac Surgery",
        "Cardiac Product",
        "Heart Valves",
        "Cardiac Surgery",
        "Generic",
        "Abdominal Aortic Aneurysm",
        "Anastomosis",
        "Aneurysm Repair",
        "Anticoagulation",
        "Aortic Arch",
        "Aortic Clamp",
        "Aortic Dissection",
        "Aortic Root",
        "Aortic Valve",
        "Arteriotomy",
        "Ascending Aorta",
        "Atrial Fibrillation",
        "Atrial Septal Defect",
        "Calcification",
        "Cardiac Output",
        "Cardiomyopathy",
        "Cardioplegia",
        "Cardioplegic Solution",
        "Cardiopulmonary Bypass",
        "Chordae Tendineae",
        "Commissure",
        "Coronary Artery Bypass GraPing",
        "Cross Clamp",
        "Defibrillator",
        "Dilated Cardiomyopathy",
        "Echocardiography",
        "Ejection Fraction",
        "Endarterectomy",
        "Endocarditis",
        "Endovascular Surgery",
        "Extracorporeal Membrane Oxygenation",
        "Fluoroscopy",
        "GraP",
        "Heart Lung Machine",
        "Hemodynamics",
        "Hemostasis",
        "Hybrid Operating Room",
        "Hypertrophic Cardiomyopathy",
        "Infective Endocarditis",
        "Intensive Care Unit",
        "Intra Aortic Balloon Pump",
        "Intraoperative Imaging",
        "Intraoperative Monitoring",
        "Leaflet",
        "LeP Atrial Appendage",
        "Maze Procedure",
        "Minimally Invasive Cardiac Surgery",
        "Mitral Valve",
        "Myocardial Protection",
        "Off Pump CABG",
        "On Pump CABG",
        "Pacemaker",
        "Patch GraP",
        "Patent Foramen Ovale",
        "Perfusionist",
        "Pericarditis",
        "Postoperative Care",
        "Protamine",
        "Pulmonary Valve",
        "Reoperation",
        "Restrictive Cardiomyopathy",
        "Robotic Assisted Cardiac Surgery",
        "Septal Defect",
        "Sternotomy",
        "Stroke Volume",
        "Thoracotomy",
        "Transesophageal Echocardiography",
        "Tricuspid Valve",
        "Valve Annulus",
        "Valve Regurgitation",
        "Valve Stenosis",
        "Ventricular Septal Defect",
        "Ventriculotomy",
        "Weaning from Bypass",
        "Cardiac Surgery",
        "Cardiac Product",
        "Acute Coronary Syndrome",
        "Anesthesia",
        "Angioplasty",
        "Anticoagulation Therapy",
        "Aortic Arch",
        "Aortic Valve",
        "Ascending Aorta",
        "Balloon Angioplasty",
        "Balloon Deflation",
        "Balloon Diameter",
        "Balloon Inflation",
        "Balloon Length",
        "Balloons for PTCA Percutaneous Transluminal Coronary Angioplasty",
        "Blood Flow Dynamics",
        "Cardiac Arrest",
        "Cardiac Function",
        "Cardiac Monitoring",
        "Cardiac Output",
        "Cardiac Rehabilitation",
        "Cardiac Rhythm Management",
        "Cardiac Support Devices",
        "Cardiogenic Shock",
        "Cardiopulmonary Bypass",
        "Catheter Insertion Site",
        "Catheter Removal",
        "Catheterization",
        "Clinical Trials",
        "Coronary Angiography",
        "Coronary Artery Bypass GraPing",
        "Coronary Artery Disease",
        "Coronary Bypass",
        "Coronary Occlusion",
        "Coronary Perfusion Pressure",
        "Coronary Revascularization",
        "Counterpulsation",
        "Deflation Rate",
        "Descending Aorta",
        "Device Calibration",
        "Device Maintenance",
        "Device Sterilization",
        "Diastolic Dysfunction",
        "Drug Eluting Balloon",
        "Emergency Care",
        "Endothelial Function",
        "Endovascular Procedure",
        "Fractional Flow Reserve",
        "Guidewire",
        "Heart Failure",
        "Heart Rate",
        "Hemodynamic Monitoring",
        "Hemodynamic Support",
        "IABP Mechanism",
        "Inflation Pressure",
        "Interventional Cardiologist",
        "Intra Aortic Balloon Catheter",
        "Intra Aortic Balloon Pump",
        "Intracoronary Shunt",
        "Intracoronary Shunt Indications",
        "Intraoperative Monitoring",
        "Intravascular Device",
        "Intravascular Ultrasound",
        "Ischemic Heart Disease",
        "LeP Ventricular Assist Device",
        "Mean Arterial Pressure",
        "Myocardial Infarction",
        "Myocardial Protection",
        "Optical Coherence Tomography",
        "Percutaneous Coronary Intervention",
        "Percutaneous Valve Intervention",
        "Postoperative Care",
        "Post Procedure Complications",
        "Pressure Monitoring",
        "Pressure Wire",
        "Prophylactic Measures",
        "Pulmonary Artery Pressure",
        "Pulse Pressure",
        "Right Ventricular Assist Device",
        "Scoring Balloon",
        "Shunt Placement Technique",
        "Stent GraP",
        "Stent Placement",
        "Surgical Approach",
        "Surgical Procedure",
        "Surgical Revascularization",
        "Surgical Team",
        "Systemic Vascular Resistance",
        "Systolic Dysfunction",
        "Thrombolysis",
        "Transcatheter Aortic Valve Replacement",
        "Transluminal Access",
        "Valve Replacement",
        "Vascular Access",
        "Vascular Access Site",
        "Vascular Closure Device",
        "Vascular Endothelial Growth Factor",
        "Vascular Health",
        "Vascular Surgeon",
        "Volume Status",
        "Cardiac Surgery",
        "Heart Valve",
        "Annuloplasty",
        "Anticoagulation Therapy",
        "Aortic Valve",
        "Balloon Valvuloplasty",
        "Bileaflet Valve",
        "Biological Valve",
        "Biomechanical Performance",
        "Bioprosthetic Valve",
        "Bovine Pericardium",
        "Caged Ball Valve",
        "Cardiac Output",
        "Cardiovascular Imaging",
        "Chordae Tendineae",
        "Commissure",
        "Coronary Sinus",
        "Durability Testing",
        "Echocardiography",
        "Ejection Fraction",
        "Endocarditis Prevention",
        "Fluoroscopy",
        "Heart Valve Prolapse",
        "Hemodynamics",
        "Hydraulic Efficiency",
        "Implant Procedure",
        "Implantable Device",
        "Implantable Valve",
        "Implantation Technique",
        "Infective Endocarditis",
        "Intraoperative Imaging",
        "Leaflet",
        "Leaflet Coaptation",
        "Long Term Outcomes",
        "Mechanical Components",
        "Mechanical Valve",
        "Mitral Valve",
        "Patient Matched Valve",
        "Pericardial Tissue",
        "Perioperative Complications",
        "Porcine Valve",
        "Post Operative Care",
        "Postoperative Monitoring",
        "Preoperative Assessment",
        "Preoperative Imaging",
        "Prosthesis",
        "Prosthetic Material",
        "Prosthetic Valve",
        "Prosthetic Valve Failure",
        "Pulmonary Valve",
        "Regurgitant Valve",
        "Regurgitation Volume",
        "Single Leaflet Valve",
        "Stenotic Valve",
        "Stent Frame",
        "Surgical Approach",
        "Surgical Mesh",
        "Surgical Valve Replacement",
        "Sutureless Valve",
        "Thrombosis Risk",
        "Tilting Disc Valve",
        "Tissue Engineering",
        "Tissue Valve",
        "Transcatheter Valve Replacement",
        "Transesophageal Echocardiography",
        "Transvalvular Gradient",
        "Tricuspid Valve",
        "Valve Annulus",
        "Valve Closure",
        "Valve Complications",
        "Valve Crimping",
        "Valve Delivery System",
        "Valve Deployment",
        "Valve Durability",
        "Valve Dysfunction",
        "Valve Fracture",
        "Valve Function",
        "Valve GraP",
        "Valve Inflation",
        "Valve Inlet",
        "Valve Leaflet Plication",
        "Valve Leaks",
        "Valve Opening",
        "Valve Outlet",
        "Valve Positioning",
        "Valve Puncture",
        "Valve Regurgitation",
        "Valve Reoperation",
        "Valve Repair",
        "Valve Repair Techniques",
        "Valve Replacement",
        "Valve Replacement Guidelines",
        "Valve Replacement Strategy",
        "Valve Risk Assessment",
        "Valve Selection Criteria",
        "Valve Sizing",
        "Valve Stenosis",
        "Valve Stenosis",
        "Valve Technology",
        "Valve Tethering",
        "Orthopedic",
        "Total Knee System",
        "Total Hip Replacement",
        "Spine",
        "Robotics",
        "Orthopedic",
        "Generic",
        "Arthroscopy",
        "Biocompatible Material",
        "Bone Awl",
        "Bone Cement Injection",
        "Bone GraPing",
        "Bone Holding Forceps",
        "Bone Ingrowth",
        "Bone Mallet",
        "Bone Marrow Edema",
        "Bone Plate",
        "Bone Screw",
        "Cartilage Repair",
        "Cerclage Wire",
        "Closed Reduction",
        "Compression Screw",
        "Decompression Surgery",
        "Degenerative Disc Disease",
        "Disc Herniation",
        "External Fixation",
        "Facet Joint",
        "Fixation Device",
        "Fixation Pin",
        "Fracture Management",
        "Fracture Plate",
        "Hip Arthroplasty",
        "Internal Fixation",
        "Intramedullary Nail",
        "Intramedullary Rod",
        "Intraoperative Navigation",
        "Joint Arthroscopy",
        "Joint Replacement",
        "Knee Arthroplasty",
        "K Wire",
        "Kyphoplasty",
        "Lag Screw",
        "Ligament Reconstruction",
        "Locking Screw",
        "Lumbosacral",
        "Meniscal Repair",
        "Myelopathy",
        "Neuromonitoring",
        "Open Reduction",
        "Orthopedic Chisel",
        "Orthopedic Drill",
        "Orthopedic Implant",
        "Orthopedic Surgery",
        "Osseointegration",
        "Osteolysis",
        "Osteophyte Removal",
        "Osteotome",
        "Periosteal Elevator",
        "Radiculopathy",
        "Reamer",
        "Reduction Clamp",
        "Sacral Screw",
        "Sagi‘al Balance",
        "Spinal Instrumentation",
        "Spinal Stenosis",
        "Spinopelvic Alignment",
        "Spondylolisthesis",
        "Surgical Retractor",
        "Surgical Saw",
        "Tendon Repair",
        "Thoracic Spine",
        "Thoracolumbar Fusion",
        "Trauma Surgery",
        "Vertebral Compression Fracture",
        "Vertebroplasty",
        "Orthopedic",
        "Total Knee System",
        "Alignment Guide",
        "Anterior Cruciate Ligament",
        "Arthroplasty",
        "Articular Cartilage",
        "Bicompartmental Knee Replacement",
        "Bone Awl",
        "Bone Cement",
        "Bone Cement Injector",
        "Bone Chisel",
        "Bone Drill",
        "Bone Holding Forceps",
        "Bone Hook",
        "Bone Mallet",
        "Bone Nibbler",
        "Cement Gun",
        "Cement Restrictor",
        "Cemented Implant",
        "Cementless Implant",
        "Cruciate Retaining Knee",
        "Cure‘e",
        "Cuang Block",
        "Distal Femoral Cuang Block",
        "Drainage Tube",
        "Extension Gap",
        "Extramedullary Alignment Guide",
        "Femoral Broach",
        "Femoral Component",
        "Femoral Condyle",
        "Femoral Elevator",
        "Femoral Impactor",
        "Femoral Resection",
        "Femoral Resector",
        "Femoral Sizer",
        "Femoral Template",
        "Femoral Trial Component",
        "Flexion Gap",
        "Hohmann Retractor",
        "Impactor",
        "Intramedullary Alignment Guide",
        "Joint Line Restoration",
        "Joint Stability",
        "Knee Distractor",
        "Langenbeck Retractor",
        "Ligament Balancer",
        "Meniscus",
        "Minimally Invasive Surgery",
        "Modular Knee System",
        "Oscillating Saw",
        "Osteotome",
        "Patella Resurfacing",
        "Patella Retractor",
        "Patellar Clamp",
        "Patellar Component",
        "Patellar Impactor",
        "Patellar Resection",
        "Patellar Sizer",
        "Patellar Trial Component",
        "Patellofemoral Arthroplasty",
        "Patient Specific Instruments",
        "Periosteal Elevator",
        "Polyethylene Insert",
        "Posterior Cruciate Ligament",
        "Posterior Stabilized Knee",
        "Postoperative Care",
        "Press Fit Implant",
        "Proximal Tibial Cuang Block",
        "Range of Motion",
        "Reduction Clamp",
        "Rehabilitation Protocol",
        "Robotic Assisted Surgery",
        "Rongeur",
        "Rotary Cuang Guide",
        "Sagi‘al Saw",
        "Screwdriver",
        "Self Retaining Retractor",
        "Skin Hook",
        "SoP Tissue Balancing",
        "SoP Tissue Retractor",
        "Spacer Block",
        "Subchondral Bone",
        "Suction Tip",
        "Surgical Retractor",
        "Surgical Saw",
        "Tibial Broach",
        "Tibial Component",
        "Tibial Elevator",
        "Tibial Impactor",
        "Tibial Plateau",
        "Tibial Plateau Leveling",
        "Tibial Resection",
        "Tibial Resector",
        "Tibial Sizer",
        "Tibial Template",
        "Tibial Trial Component",
        "Trial Reduction",
        "Trial Spacer",
        "Unicompartmental Knee Replacement",
        "Varus Valgus Alignment",
        "Wound Closure",
        "Orthopedic",
        "Total Hip Replacement",
        "Acetabular Cup",
        "Acetabular Cup Impactor",
        "Acetabular Cup Positioner",
        "Acetabular Liner",
        "Acetabular Reamer",
        "Acetabulum",
        "Alignment Jig",
        "Anterior Approach",
        "Arthroplasty",
        "Aseptic Loosening",
        "Biomechanics",
        "Bone Awl",
        "Bone Cement",
        "Bone Cement Injector",
        "Bone Chisel",
        "Bone Drill",
        "Bone Holding Forceps",
        "Bone Hook",
        "Bone Mallet",
        "Bone Nibbler",
        "Broach",
        "Cancellous Bone",
        "Cement Gun",
        "Cement Restrictor",
        "Cemented Prosthesis",
        "Cementless Prosthesis",
        "Ceramic on Ceramic",
        "Cortical Bone",
        "Cross Linked Polyethylene",
        "Cup Positioning",
        "Cup Reamer",
        "Cure‘e",
        "Dislocation",
        "Drainage Tube",
        "Dual Mobility Cup",
        "Femoral Canal",
        "Femoral Elevator",
        "Femoral Head",
        "Femoral Head Extractor",
        "Femoral Head Impactor",
        "Femoral Offset",
        "Femoral Reamer",
        "Femoral Stem",
        "Femur",
        "Fluoroscopy",
        "Hemiarthroplasty",
        "Hip Resurfacing",
        "Hohmann Retractor",
        "Impactor",
        "Intraoperative Imaging",
        "Intraoperative Navigation",
        "Joint Stability",
        "Langenbeck Retractor",
        "Lateral Approach",
        "Leg Length Discrepancy",
        "Load Bearing",
        "Metal on Metal",
        "Minimally Invasive Surgery",
        "Modular Neck",
        "Modular Prosthesis",
        "Oscillating Saw",
        "Osteointegration",
        "Osteolysis",
        "Osteotome",
        "Osteotomy",
        "Patient Specific Instruments",
        "Periosteal Elevator",
        "Periprosthetic Fracture",
        "Polyethylene Liner",
        "Posterior Approach",
        "Postoperative Care",
        "Press Fit Implant",
        "Radiolucent",
        "Radiopaque",
        "Range of Motion",
        "Rasp",
        "Reamer",
        "Reduction Clamp",
        "Revision Surgery",
        "Robotic Assisted Surgery",
        "Rongeur",
        "Sagi‘al Saw",
        "Screwdriver",
        "Self Retaining Retractor",
        "Skin Hook",
        "Stem Extractor",
        "Stem Inserter",
        "Sterile Packaging",
        "Stress Shielding",
        "Suction Tip",
        "Surgical Guide",
        "Surgical Retractor",
        "Surgical Saw",
        "Surgical Template",
        "Trial Component",
        "Trial Cup",
        "Trial Head",
        "Trial Stem",
        "Wear Rate",
        "Wound Closure",
        "Orthopedic",
        "Spine",
        "Adjacent Segment Disease",
        "Alignment Jig",
        "AllograP",
        "Annulus Fibrosus",
        "Anterior Approach",
        "Anterior Cervical Discectomy and Fusion",
        "AutograP",
        "Awl",
        "Bone Cure‘e",
        "Bone Drill",
        "Bone Elevator",
        "Bone GraP",
        "Bone Rasp",
        "Bone Retractor",
        "Bone Substitute",
        "Cage",
        "Cancellous Screw",
        "Cannulated Screw",
        "Cervical Pedicle Screw",
        "Cervical Plate",
        "Cervical Spine",
        "Compression Forceps",
        "Coronal Balance",
        "Corpectomy",
        "Cortical Screw",
        "Cross Connector",
        "Cure‘e",
        "Degenerative Disc Disease",
        "Disc Space Preparation",
        "Discectomy",
        "Distraction Forceps",
        "Drill Guide",
        "Expandable Cage",
        "Facet Joint",
        "Fluoroscopy",
        "Foraminotomy",
        "Fusion Rate",
        "GraP Holder",
        "GraP Impactor",
        "Implant Inserter",
        "Interbody Fusion Device",
        "Interbody Spacer",
        "Intervertebral Disc",
        "Intraoperative Imaging",
        "Kerrison Rongeur",
        "Kyphosis",
        "Laminectomy",
        "Laminectomy Punch",
        "Lateral Approach",
        "Lateral Lumbar Interbody Fusion",
        "Lordosis",
        "Lumbar Spine",
        "Minimally Invasive Surgery",
        "Monoaxial Screw",
        "Navigation System",
        "Nerve Hook",
        "Nerve Retractor",
        "Nerve Root",
        "Nucleus Pulposus",
        "Occiput",
        "Osteotome",
        "Pedicle",
        "Pedicle Screw",
        "PEEK Cage",
        "Polyaxial Screw",
        "Posterior Approach",
        "Posterior Cervical Fusion",
        "Posterior Lumbar Interbody Fusion",
        "Postoperative Care",
        "Reduction Forceps",
        "Robotic Assisted Surgery",
        "Rod",
        "Rod Bender",
        "Rod Cu‘er",
        "Rod Inserter",
        "Rod Passer",
        "Sacroiliac Joint",
        "Sagi‘al Balance",
        "Scoliosis",
        "Screw Inserter",
        "Screwdriver",
        "Spinal Canal",
        "Spinal Cord",
        "Spinal Fusion",
        "Spinal Stenosis",
        "Spinous Process",
        "Spinous Process Clamp",
        "Spondylolisthesis",
        "Stability",
        "Sterilization",
        "Surgical Guide",
        "Tap",
        "Thoracic Spine",
        "Thoracolumbar Junction",
        "Titanium Cage",
        "Transforaminal Lumbar Interbody Fusion",
        "Transverse Process",
        "Trial Spacer",
        "Vertebrae",
        "Vertebrectomy",
        "Orthopedic",
        "Robotics",
        "3D Imaging",
        "3D Reconstruction",
        "Acetabular Component",
        "Acetabular Guide",
        "Acetabular Reamer",
        "Acetabular Resection Guide",
        "Acetabulum",
        "Active Robotics",
        "Alignment Verification",
        "Anatomic Landmarks",
        "Articular Cartilage",
        "Bone Cement",
        "Bone Model",
        "Bone Morphology",
        "Bone Preparation",
        "Bone Resection",
        "Calibration Check",
        "Cemented Fixation",
        "Cementless Fixation",
        "Complication Rate",
        "Component Sizing",
        "CT Scan",
        "Cuang Block",
        "Dynamic Assessment",
        "Electromagnetic Tracking",
        "Extension Gap",
        "Femoral Component",
        "Femoral Condyle",
        "Femoral Guide",
        "Femoral Head",
        "Femoral Resection Guide",
        "Femoral Sizer",
        "Flexion Gap",
        "Force Sensors",
        "Haptic Feedback",
        "Implant Durability",
        "Implant Kinematics",
        "Implant Positioning",
        "Implant Stability",
        "Instrument Docking",
        "Intraoperative Adjustments",
        "Intraoperative Imaging",
        "Intraoperative Navigation",
        "Joint Alignment",
        "Joint Kinematics",
        "Joint Line Restoration",
        "Joint Stability",
        "Kinematics",
        "Minimally Invasive Surgery",
        "Modular Implants",
        "MRI",
        "Operating Room Integration",
        "Optical Tracking",
        "Partial Joint Replacement",
        "Passive Robotics",
        "Patient Matched Technology",
        "Patient Specific Instrumentation",
        "Periprosthetic Joint",
        "Polyethylene Insert",
        "Postoperative Care",
        "Postoperative Evaluation",
        "Precision Cuang",
        "Preoperative Planning",
        "Preoperative Scanning",
        "Press Fit",
        "Prosthetic Alignment",
        "Radiopaque Markers",
        "Range of Motion",
        "Real Time Feedback",
        "Recovery Time",
        "Registration Process",
        "Rehabilitation Protocol",
        "Robotic Arm",
        "Robotic Arm Trajectory",
        "Robotic Calibration",
        "Robotic Assisted Surgery",
        "SoP Tissue Balancing",
        "SoP Tissue Management",
        "SoPware Update",
        "Sterile Field",
        "Subchondral Bone",
        "Surgeon Console",
        "Surgeon Ergonomics",
        "Surgeon Interface",
        "Surgical Accuracy",
        "Surgical Planning SoPware",
        "Surgical Robot",
        "Surgical Workflow",
        "System Maintenance",
        "Tibial Component",
        "Tibial Guide",
        "Tibial Plateau",
        "Tibial Resection Guide",
        "Tibial Sizer",
        "Tissue Protection",
        "Total Joint Replacement",
        "Tracking System",
        "Trial Implants",
        "Virtual Boundaries",
        "Visual Navigation",
        "Wear Pa‘erns",
        "Endo Surgery",
        "Sutures",
        "Staplers",
        "Hernia Mesh",
        "Biosurgicals",
        "Women Healthcare",
        "Endo Surgery",
        "Generic",
        "Adhesion Prevention",
        "Anastomosis",
        "Antibacterial Coating",
        "Aponeurosis",
        "Bipolar Energy",
        "Blunt Dissection",
        "Capillary Action",
        "Carcinoma",
        "Coagulation",
        "Colostomy",
        "Cuang Needle",
        "Dissection",
        "Doxorubicin",
        "Electrosurgery",
        "Endoscopic Surgery",
        "Endotoxin",
        "Epidural Hematoma",
        "Ethylene Oxide Sterilization",
        "Fascial Closure",
        "Fibrin Glue",
        "Fixation Device",
        "Gastrointestinal Anastomosis",
        "Hemostasis",
        "Hemostatic Agent",
        "Hydrogel",
        "Hydrolysis",
        "Intraoperative Complication",
        "Laparoscopy",
        "Ligature",
        "Lymphadenectomy",
        "Mastectomy",
        "Microbial Barrier",
        "Minimally Invasive Surgery",
        "Mucosal Repair",
        "Omentoplasty",
        "Peritoneum",
        "Postoperative Adhesion",
        "Radiopaque",
        "Rectus Sheath",
        "Seroma Prevention",
        "Sterile Field",
        "Thoracoscopic Surgery",
        "Tissue Approximation",
        "Tissue Integrity",
        "Tissue Reinforcement",
        "Trocar",
        "Trocar Site Closure",
        "Wound Closure",
        "Wound Healing",
        "Wound Infection",
        "Wound Retraction",
        "Wound Strength",
        "Z Stitch",
        "Endo Surgery",
        "Sutures",
        "Absorbable Suture",
        "Anastomosis",
        "Anesthesia",
        "Antimicrobial Coating",
        "Aortic Valve",
        "Arterial GraP",
        "Atrial Septal Defect",
        "Bicaval Technique",
        "Bicuspid Valve",
        "Blunt Dissection",
        "Braided Suture",
        "Bypass Surgery",
        "Cardioplegia",
        "Cardiopulmonary Bypass",
        "Carotid Artery",
        "Cauterization",
        "Corneal Transplant",
        "Coronary Artery Bypass GraPing",
        "Cryoablation",
        "Dermatoplasty",
        "Diathermy",
        "Electrocautery",
        "Endothelial Cells",
        "Epicardium",
        "Ethicon Sutures",
        "Extracorporeal Membrane Oxygenation",
        "Femoral Artery",
        "Fibroplasia",
        "Fixation Suture",
        "Gore Tex Suture",
        "Heart Valve Replacement",
        "Hemostasis",
        "Hydrodissection",
        "Hypertrophic Scar",
        "Intrastromal Suture",
        "Knot Security",
        "Ligation Clips",
        "Ligature",
        "Linear Stapler",
        "Mastectomy",
        "Mitral Valve",
        "Monofilament Suture",
        "Non absorbable Suture",
        "Ocular Trauma",
        "Oculoplastic Surgery",
        "Open Heart Surgery",
        "Ophthalmic Suture",
        "Optic Nerve",
        "Patch GraP",
        "Pericardium",
        "Plastic Surgery",
        "Polypropylene Suture",
        "Postoperative Complication",
        "Prosthetic Valve",
        "Refractive Surgery",
        "Retention Suture",
        "Retinal Detachment",
        "Retinal Rea‘achment",
        "Saphenous Vein",
        "Scalp Closure",
        "Scar Revision",
        "Silk Suture",
        "Skin GraP",
        "Spatulated Needle",
        "Stainless Steel Suture",
        "Stenosis",
        "Sterile Technique",
        "Sternotomy",
        "Subcutaneous Tissue",
        "Suture Needle",
        "Suture Passer",
        "Tensile Strength",
        "Tissue Adhesive",
        "Tissue Bank",
        "Tissue Expansion",
        "Tissue Perfusion",
        "Transcatheter Aortic Valve Replacement",
        "Tricuspid Valve",
        "Trocar",
        "Valve Annulus",
        "Valve Leaflet",
        "Valve Repair",
        "Vascular GraP",
        "Vessel Ligation",
        "Vitrectomy",
        "Wound Closure",
        "Endo Surgery",
        "Staplers",
        "Absorbable Clip",
        "Adhesion",
        "Anastomosis",
        "Aneurysm",
        "Antimicrobial Coating",
        "Aorta",
        "Aortic Clamping",
        "Arterial Ligation",
        "Arteriosclerosis",
        "Bariatric Surgery",
        "Biliary Clip",
        "Blunt Dissection",
        "Bypass GraPing",
        "Capillary Action",
        "Cardiovascular Surgery",
        "Cauterization",
        "Clip Cartridge",
        "Clip Applicator",
        "Clip Deployment",
        "Clip Ligator",
        "Clip Retraction",
        "Closure Integrity",
        "Colorectal Surgery",
        "Cuang Stapler",
        "Dermal Stapler",
        "Dissection",
        "Electrosurgery",
        "Endoscopic Clip",
        "Endoscopic Stapler",
        "Endoscopic Surgery",
        "Endothelial Cells",
        "Eversion Technique",
        "Femoral Artery",
        "Fixation Clip",
        "Fixation Suture",
        "General Surgery",
        "Gastroplasty",
        "Gynecologic Surgery",
        "Hemostasis",
        "Herniorrhaphy",
        "Hydrolysis",
        "Intraoperative Hemorrhage",
        "Knot Security",
        "Laparoscopic Clip",
        "Laparoscopic Stapler",
        "Laparoscopy",
        "Ligation",
        "Linear Stapler",
        "Loop Ligation",
        "Lumen Closure",
        "Minimally Invasive Surgery",
        "Monofilament Suture",
        "Non absorbable Clip",
        "Non absorbable Stapler",
        "Open Surgery",
        "Peritoneal Closure",
        "Prophylactic Clip",
        "Radiopaque Clip",
        "Rectus Sheath",
        "Retention Suture",
        "Saphenous Vein",
        "Serrated Stapler",
        "Skin Stapler",
        "Sphincterotomy",
        "Spinal Surgery",
        "Staple Line",
        "Staple Removal",
        "Stainless Steel Stapler",
        "Stenosis",
        "Sterile Field",
        "Sternotomy",
        "Subcutaneous Closure",
        "Tissue Approximation",
        "Tissue Adhesive",
        "Tissue Integrity",
        "Tissue Perfusion",
        "Transanal Surgery",
        "Trocar Site",
        "Trocar Sterilization",
        "Vascular Clip",
        "Vascular Stapler",
        "Vein GraP",
        "Vessel Ligation",
        "Wound Closure",
        "Wound Healing",
        "Wound Reinforcement",
        "Endo Surgery",
        "Hernia Mesh",
        "Abdominal Wall",
        "Adhesion",
        "Anterior Abdominal Wall",
        "Anterior Repair",
        "Aponeurosis",
        "Bassini technique",
        "Biocompatibility",
        "Biological Mesh",
        "Biomaterial",
        "Burst Strength",
        "Carcinoma",
        "Chronic Pain",
        "Coated Mesh",
        "Collagen",
        "Comorbidities",
        "Composite Mesh",
        "CT Scan",
        "Defect Size",
        "Direct Hernia",
        "Dissection",
        "EHS Classification",
        "Endoscopic Repair",
        "Epigastric Hernia",
        "Erosion",
        "eTEP",
        "Extraperitoneal",
        "Femoral Hernia",
        "Fixation Device",
        "Fixation Suture",
        "Foreign Body Reaction",
        "Hernia Mesh",
        "Hernioplasty",
        "Herniorrhaphy",
        "Herniotomy",
        "Hydrolysis",
        "Incisional Hernia",
        "Indirect Hernia",
        "Inferior Epigastric Artery",
        "Inguinal Hernia",
        "Inlay Mesh",
        "Laparoscopic Hernia Repair",
        "Laparoscopy",
        "Lichtenstein technique",
        "Lightweight Mesh",
        "Macroporous Mesh",
        "Mesh Adhesion",
        "Mesh Plug",
        "Mesh Reinforcement",
        "Mesh Shrinkage",
        "Minimally Invasive Surgery",
        "Morbidity",
        "Multifilament Mesh",
        "Myofascial Defect",
        "Myopectineal orifice",
        "Non absorbable Mesh",
        "Occlusion",
        "Omentum",
        "Onlay Mesh",
        "Open Hernia Repair",
        "Parastomal Hernia",
        "Parietal Peritoneum",
        "Patch Repair",
        "Peritoneal Adhesion",
        "Peritoneal Cavity",
        "Peritoneal Defect",
        "Polypropylene Mesh",
        "Postoperative Complication",
        "Preperitoneal Space",
        "Primary Closure",
        "Prophylactic Mesh",
        "Prosthetic Mesh",
        "Rectus Abdominis",
        "Recurrence Rate",
        "Recurrent Hernia",
        "Retrorectus Repair",
        "Sacralization",
        "Seroma",
        "Shouldice technique",
        "Small Bowel Obstruction",
        "Spigelian hernia",
        "Sterile Field",
        "Strangulated Hernia",
        "Subcutaneous Emphysema",
        "Subfascial Mesh",
        "Surgical Mesh",
        "Surgical Site Infection",
        "Tension free Repair",
        "Tissue Adhesion",
        "Tissue Approximation",
        "Tissue Integration",
        "Tissue Reinforcement",
        "Tissue Repair",
        "Total Extraperitoneal Repair",
        "Transabdominal Preperitoneal Repair",
        "Transverse Abdominis Release",
        "Trocar Placement",
        "Umbilical Hernia",
        "Ventral Hernia",
        "Visceral Adhesion",
        "Visceral Sac",
        "Wound Closure",
        "Wound Healing",
        "Wound Infection",
        "Wound Reinforcement",
        "Wound Retraction",
        "Wound Seroma",
        "Wound Strength",
        "Zinc Oxide Mesh",
        "Endo Surgery",
        "Biosurgicals",
        "Absorbable Hemostat",
        "Active hemostatic agents",
        "Adhesive Strength",
        "Albumin Glutaraldehyde",
        "Anastomosis",
        "Antimicrobial",
        "Aortic Dissection",
        "Autologous Fibrin",
        "Bacteriostatic",
        "Biocompatibility",
        "Biofunctionalization",
        "Biopolymer",
        "Blood Coagulation",
        "Blood Loss",
        "Blood Platelets",
        "Bone Wax",
        "Bovine Collagen",
        "Calcium Alginate",
        "Capillary Action",
        "Chitosan Hemostat",
        "Clot Formation",
        "Collagen Fibrils",
        "Collagen Sponge",
        "Compressive Hemostasis",
        "Contact Activation",
        "Cryo adhesive",
        "Cyanoacrylate",
        "Cytotoxicity",
        "Dermal Adhesive",
        "Dermatoplasty",
        "Electrocautery",
        "Endoscopic Hemostasis",
        "Epinephrine",
        "Fibrin Adhesive",
        "Fibrin Clot",
        "Fibrin Sealant",
        "Fibrinogen",
        "Fibroblast Adhesion",
        "Flowable Matrix",
        "Gelatin Matrix",
        "Gelfoam",
        "Gluing Agent",
        "Glycolic Acid",
        "Haemostatic Dressing",
        "Haemostatic Powder",
        "Hemorrhage",
        "Hemorrhoidectomy",
        "Hemostasis",
        "Hemostatic Agent",
        "Hemostatic Clip",
        "Hemostatic Gauze",
        "Hemostatic Powder",
        "Intraoperative Bleeding",
        "Intraperitoneal Adhesions",
        "Laparoscopic Hemostasis",
        "Laser Hemostasis",
        "Ligature",
        "Liquid Adhesive",
        "Microfibrillar Collagen",
        "Monomer",
        "Oxidized Cellulose",
        "Passive Hemostatic Agent",
        "Pneumatic Tourniquet",
        "Polyethylene Glycol",
        "Polymerization",
        "Procoagulant",
        "Resorbable Hemostat",
        "Sclerosant",
        "Sealant",
        "Skin Closure",
        "Skin GraP",
        "Skin Sealant",
        "Sodium Carboxymethylcellulose",
        "Spray Adhesive",
        "Staple Reinforcement",
        "Sterile Technique",
        "Sternal Closure",
        "Sutureless Closure",
        "Sutureline Reinforcement",
        "Tachocomb",
        "Tannic Acid",
        "Thrombin",
        "Tissue Adhesive",
        "Tissue Approximation",
        "Tissue Healing",
        "Tissue Integration",
        "Tissue Repair",
        "Tissue Sealant",
        "Topical Hemostat",
        "Topical Sealant",
        "Toxicity",
        "Tranexamic Acid",
        "Vascular Closure",
        "Vascular Surgery",
        "Viscoelasticity",
        "Wound Adhesive",
        "Wound Closure",
        "Wound Healing",
        "Wound Hemostasis",
        "Wound Repair",
        "Wound Sealing",
        "Wound Sterilization",
        "Zinc Oxide Adhesive",
        "Endo Surgery",
        "Women Healthcare",
        "Amenorrhea",
        "Androgen",
        "Anovulation",
        "Aromatase Inhibitor",
        "Atrophic Endometrium",
        "Bacterial Vaginosis",
        "Breakthrough Bleeding",
        "Cervical Canal",
        "Cervical Dilator",
        "Cervical Dysplasia",
        "Cervical Stenosis",
        "Cervicitis",
        "Cervix",
        "Chlamydia",
        "Contraceptive Failure Rate",
        "Contraceptive Implant",
        "Contraceptive Patch",
        "Corpus Luteum",
        "Cystitis",
        "Depot Medroxyprogesterone Acetate",
        "Dysmenorrhea",
        "Dyspareunia",
        "Ectopic Pregnancy",
        "Endometrial Ablation",
        "Endometrial Biopsy",
        "Endometrial Hyperplasia",
        "Endometrial Lining",
        "Endometrial Thickness",
        "Endometriosis",
        "Endometrium",
        "Estradiol",
        "Estrogen",
        "Fallopian Tubes",
        "Fertility Awareness",
        "Fibroid",
        "Follicle Stimulating Hormone",
        "Functional Ovarian Cyst",
        "Gonadotropin Releasing Hormone",
        "Hormonal Balance",
        "Hormonal IUD",
        "Human Chorionic Gonadotropin",
        "Hysterectomy",
        "Hysterosalpingography",
        "Hysteroscopy",
        "Intrauterine Contraceptive Device",
        "Intrauterine Insemination",
        "Intrauterine System",
        "Laparoscopy",
        "Leiomyoma",
        "Levonorgestrel",
        "Luteal Phase",
        "Luteinizing Hormone",
        "Menarche",
        "Menometrorrhagia",
        "Menopause",
        "Menorrhagia",
        "Menstruation",
        "Mirena",
        "Oophorectomy",
        "Ovarian Cyst",
        "Ovarian Reserve",
        "Ovarian Torsion",
        "Ovary",
        "Ovulation",
        "Ovulation Predictor Kit",
        "Pelvic Inflammatory Disease",
        "Pelvic Ultrasound",
        "Perimenopause",
        "Polycystic Ovary Syndrome",
        "Postcoital Bleeding",
        "Postmenopausal",
        "Premature Ovarian Failure",
        "Premenstrual Syndrome",
        "Progesterone",
        "Progestin",
        "Reproductive Endocrinology",
        "Salpingectomy",
        "Salpingitis",
        "Spermicide",
        "Sterilization",
        "Subdermal Implant",
        "Submucosal Fibroid",
        "Subserosal Fibroid",
        "Tamoxifen",
        "T shaped IUD",
        "Tubal Ligation",
        "Uterine Artery Embolization",
        "Uterine Fibroid",
        "Uterine Polyps",
        "Uterus",
        "Vaginal Atrophy",
        "Vaginal Bleeding",
        "Vaginal Discharge",
        "Vaginal Estrogen",
        "Vaginal Ring",
        "Vaginitis",
        "Vulvovaginitis",
        "Withdrawal Bleeding",
        "Women’s Health",
        "Zygote",
        "Diagnostics",
        "Rapid Testing",
        "Regents",
        "Instruments",
        "Diagnostics",
        "Generic",
        "Accreditation",
        "Amplicon",
        "Analytical Sensitivity",
        "Analytical Specificity",
        "Antibody",
        "Antigen",
        "Assay",
        "Automation",
        "Batch Testing",
        "Bioluminescence",
        "Biopsy",
        "Blinding",
        "Buffer",
        "Calibrator",
        "Chemiluminescence",
        "Chromatography",
        "Clinical Trial",
        "Compliance",
        "Control",
        "Cross reactivity",
        "Cut off Threshold",
        "Cut off Value",
        "Cytology",
        "Diagnostic Sensitivity",
        "Diagnostic Specificity",
        "Diluent",
        "DNA Extraction",
        "Double Blind Study",
        "Droplet Digital PCR",
        "Electrophoresis",
        "ELISA Enzyme Linked Immunosorbent Assay",
        "End Point Assay",
        "Enzyme Substrate",
        "Ex Vivo",
        "False Negative",
        "False Positive",
        "Flow Cytometry",
        "Fluorescence",
        "Fluorescent Antibody",
        "Genotyping",
        "Histopathology",
        "Hybridization",
        "Immunoassay",
        "Immunohematology",
        "Immunohistochemistry",
        "In Vitro",
        "In Vivo",
        "Incubation Time",
        "Interference",
        "ISO 1518ti",
        "Kinetic Assay",
        "Limit of Detection",
        "Limit of Quantitation",
        "Linearity",
        "Matrix",
        "Microarray",
        "Molecular Diagnostics",
        "Monoclonal Antibody",
        "Multiplexing",
        "Negative Predictive Value",
        "Nephelometry",
        "Next Generation Sequencing",
        "Northern Blot",
        "PCR Polymerase Chain Reaction",
        "Phenotyping",
        "Point of Care Testing",
        "Polyclonal Antibody",
        "Positive Predictive Value",
        "Primer",
        "Probe",
        "Proficiency Testing",
        "qPCR Quantitative PCR",
        "Quality Assurance",
        "Quality Control",
        "Randomized Control Trial",
        "Reagent",
        "Reference Range",
        "Regulatory Affairs",
        "RNA Extraction",
        "RTPCR Reverse Transcriptase PCR",
        "Sample Preparation",
        "Sensitivity",
        "Serology",
        "Southern Blot",
        "Specificity",
        "Specimen Collection",
        "Spectrophotometry",
        "Stability",
        "Standard Operating Procedure",
        "Throughput",
        "Titer",
        "Transport Medium",
        "Turbidimetry",
        "Turnaround Time",
        "Validation",
        "Verification",
        "Western Blot",
        "Diagnostics",
        "Rapid Testing Kits",
        "Absorbent Pad",
        "Analytical Interference",
        "Analytical Phase",
        "Analytical Sensitivity",
        "Analytical Specificity",
        "Antibody",
        "Antigen",
        "Aseptic Technique",
        "Assay",
        "Batch Number",
        "Biosafety Level",
        "Buffer",
        "Calibration",
        "Capillary Action",
        "Casse‘e",
        "CE Marking",
        "Chromatographic Separation",
        "Clinical Interference",
        "Clinical Sample",
        "Colloidal Gold",
        "Compliance Labeling",
        "Conjugate Pad",
        "Control Line",
        "Cross reactivity",
        "Cut off Threshold",
        "Cut off Value",
        "Desiccant",
        "Diagnostic Accuracy",
        "Diagnostic Sensitivity",
        "Diagnostic Specificity",
        "Diluent",
        "Enzyme Substrate Reaction",
        "Expiry Date",
        "False Negative",
        "False Negative Rate",
        "False Positive",
        "False Positive Rate",
        "FDA Approval",
        "Flow Control",
        "Flow Rate",
        "Fluorescence",
        "Immunochromatography",
        "In Vitro Diagnostics",
        "Incubation Period",
        "Instruction for Use",
        "Interference",
        "Interpretation",
        "ISO 13485 Quality Management System for Medical Devices",
        "Labeling Requirements",
        "Lateral Flow Assay",
        "Limit of Detection",
        "Limit of Quantitation",
        "Linearity",
        "Lot Number",
        "Matrix Effect",
        "Negative Control",
        "Negative Predictive Value",
        "Nitrocellulose Membrane",
        "Operator Training",
        "Point of Care Testing",
        "Positive Control",
        "Positive Predictive Value",
        "Post analytical Phase",
        "Pre analytical Phase",
        "Proficiency Testing",
        "Quality Assurance",
        "Quality Control",
        "Rapid Diagnostic Test",
        "Reaction Kinetics",
        "Reagent",
        "Reagent Blank",
        "Regulatory Compliance",
        "Result Window",
        "Risk Management",
        "Sample Dilution",
        "Sample Pad",
        "Sample Type e",
        "g",
        "Blood",
        "Saliva",
        "Urine",
        "Sample Volume",
        "Sensitivity",
        "Sensitivity Analysis",
        "Shelf Life",
        "Signal Intensity",
        "Specificity",
        "Specificity Analysis",
        "Specimen Collection",
        "Specimen Integrity",
        "Stability",
        "Sterility",
        "Storage Conditions",
        "Strip Test",
        "Substrate",
        "Technical Documentation",
        "Test Cartridge",
        "Test Line",
        "Test Principle",
        "Transport Medium",
        "Turnaround Time",
        "User Error",
        "Validation",
        "Verification",
        "Diagnostics",
        "Reagents",
        "Absorbance",
        "Affinity",
        "Aliquot",
        "Analytical Phase",
        "Analytical Reagent",
        "Analytical Sensitivity",
        "Analytical Specificity",
        "Antibody",
        "Antigen",
        "Aseptic Technique",
        "Avidity",
        "Batch Number",
        "Biocompatibility",
        "Bioluminescence",
        "Biosafety Level",
        "Buffer",
        "Calibration",
        "Calibrator",
        "CE Marking",
        "Centrifugation",
        "Centrifuge Tube",
        "Chemiluminescence",
        "Chromatography",
        "Clinical Reagent",
        "Concentration",
        "Conjugate",
        "Control",
        "Cross reactivity",
        "Decontamination",
        "Diagnostic Reagent",
        "Diluent",
        "Dilution Factor",
        "Electrophoresis",
        "ELISA Enzyme Linked Immunosorbent Assay",
        "End Point Assay",
        "Enzyme",
        "Enzyme Substrate Reaction",
        "Expiry Date",
        "FDA Approval",
        "Filtration",
        "Fluorescence",
        "Hybridization",
        "Immunoassay",
        "Immunochromatography",
        "Incubation Period",
        "Instruction for Use",
        "Interference",
        "ISO 13485",
        "Kinetic Assay",
        "Lateral Flow Assay",
        "Limit of Detection",
        "Limit of Quantitation",
        "Linearity",
        "Lot Number",
        "Lysis Buffer",
        "Matrix Effect",
        "Molarity",
        "Multiplexing",
        "Negative Control",
        "Nephelometry",
        "Optical Density",
        "Optical Density",
        "pH",
        "Pipe‘e",
        "Pipeang Technique",
        "Positive Control",
        "Post analytical Phase",
        "Pre analytical Phase",
        "Proficiency Testing",
        "qPCR Quantitative PCR",
        "Quality Assurance",
        "Quality Control",
        "Reaction Buffer",
        "Reaction Kinetics",
        "Reagent Blank",
        "Reagent Grade",
        "Reagent Handling",
        "Reagent Storage",
        "Reference Standard",
        "Regulatory Compliance",
        "RTPCR Reverse Transcriptase PCR",
        "Safety Data Sheet",
        "Sample Preparation",
        "Sample Volume",
        "Shelf Life",
        "Signal Amplification",
        "Specimen Collection",
        "Spectrophotometry",
        "Stability",
        "Standard Curve",
        "Sterility",
        "Substrate",
        "Titer",
        "Transport Medium",
        "Turbidimetry",
        "Turnaround Time",
        "Validation",
        "Verification",
        "Volumetric Flask",
        "Diagnostics",
        "Instruments",
        "Accuracy",
        "Alignment",
        "Analytical Phase",
        "Analyzer",
        "Autoclave",
        "Automation",
        "Benchmarking",
        "Biochemical Analyzer",
        "Bioluminescence Reader",
        "Biosafety Level",
        "Blood Gas Analyzer",
        "Calibration",
        "Calibration Standards",
        "Carrier Plate",
        "CE Marking",
        "Centrifuge",
        "Centrifuge Tube",
        "Chromatograph",
        "Clinical Chemistry Analyzer",
        "Confocal Microscope",
        "Data Acquisition",
        "Data Analysis",
        "Digital Microscope",
        "DNA Sequencer",
        "Electrolyte Analyzer",
        "Electrophoresis",
        "ELISA Plate Reader",
        "Environmental Controls",
        "Ergonomics",
        "Error Rate",
        "FDA Approval",
        "Flow Chamber",
        "Flow Cytometer",
        "Fluorescence Reader",
        "Freezer",
        "Fume Hood",
        "Gas Chromatograph",
        "Hematology Analyzer",
        "Homogenizer",
        "Immunoassay Reader",
        "Immunohematology Analyzer",
        "Incubator",
        "Instrument Calibration",
        "Instrument Control",
        "Instrument Error",
        "ISO 13485 Medical Devices",
        "Limit of Detection",
        "Limit of Quantitation",
        "Maintenance",
        "Mass Spectrometer",
        "Micropipe‘e",
        "Microplate Reader",
        "Microscope",
        "Nephelometer",
        "Operation Manual",
        "Osmometer",
        "PCR Machine",
        "Performance Validation",
        "pH Meter",
        "Phase Contrast Microscope",
        "Pipe‘e",
        "Post analytical Phase",
        "Pre analytical Phase",
        "Precision",
        "Quality Assurance",
        "Quality Control",
        "Reagent Compatibility",
        "Real Time PCR qPCR",
        "Refrigerator",
        "Regulatory Compliance",
        "RNA Extractor",
        "Safety Features",
        "Sample Holder",
        "Sample Loading",
        "Sample Preparation",
        "Scanning Electron Microscope",
        "Sensitivity",
        "Service Contract",
        "Shaker",
        "SoPware Interface",
        "Specificity",
        "Spectral Analyzer",
        "Spectrometer",
        "Spectrophotometer",
        "Standard Operating Procedure",
        "Syringe Pump",
        "System Integration",
        "Technical Support",
        "Thermocycler",
        "Throughput",
        "Throughput Capacity",
        "Transmission Electron Microscope",
        "Turbidimeter",
        "Turnaround Time",
        "Ultrasonicator",
        "Urinalysis Machine",
        "User Interface",
        "User Training",
        "Vortex Mixer",
        "Warranty",
        "ENT",
        "Coagulation System",
        "Nasal Packing",
        "Sinus Balloons",
        "Airway Management Devices",
        "ENT",
        "Generic",
        "Adenoidectomy",
        "Adenoids",
        "Allergic Rhinitis",
        "Anosmia",
        "Antrochoanal Polyp",
        "Apnea",
        "Audiogram",
        "Audiometry",
        "Bronchoscopy",
        "Cauterization",
        "Chronic Otitis Media",
        "Chronic Rhinosinusitis",
        "Concha Bullosa",
        "Cricothyrotomy",
        "Decongestant",
        "Dysphagia",
        "Dysphonia",
        "Eardrum Perforation",
        "Electrocautery",
        "Endolymphatic Hydrops",
        "Endoscopic Sinus Surgery",
        "Epigloatis",
        "Epistaxis",
        "Esophagoscopy",
        "Ethmoidectomy",
        "Eustachian Tube Dysfunction",
        "Fibroptic Laryngoscopy",
        "Gloas",
        "Hemostasis",
        "Hypernasality",
        "Hypopharynx",
        "Inferior Turbinate",
        "Intubation",
        "Laryngectomy",
        "Laryngitis",
        "Laryngopharyngeal Reflux",
        "Laryngoscope",
        "Laryngospasm",
        "Larynx",
        "Mastoidectomy",
        "Maxillary Sinus",
        "Meniere’s Disease",
        "Microlaryngoscopy",
        "Myringoplasty",
        "Myringotomy",
        "Nasal Endoscopy",
        "Nasal Polyp",
        "Nasal Vestibulitis",
        "Nasopharynx",
        "Otalgia",
        "Otolaryngology",
        "Otosclerosis",
        "Paranasal Sinuses",
        "Pharyngitis",
        "Pharyngoplasty",
        "Pharyngoscopy",
        "Polypectomy",
        "Postnasal Drip",
        "Rhinitis Medicamentosa",
        "Rhinoplasty",
        "Rhinorrhea",
        "Rhinosinusitis",
        "Septoplasty",
        "Septum Deviation",
        "Sinus Ostium",
        "Sinusitis",
        "Sleep Apnea",
        "Snoring",
        "SoP Palate",
        "Speech Pathology",
        "Sphenoid Sinus",
        "Stapedectomy",
        "Stenosis",
        "Stridor",
        "Subgloac Stenosis",
        "Tonsillectomy",
        "Tonsillitis",
        "Tympanic Membrane",
        "Tympanoplasty",
        "Uvulopalatopharyngoplasty",
        "Vocal Cord Paralysis",
        "Vocal Cord Polyp",
        "Vocal Fold Nodules",
        "Voice Therapy",
        "Weber Test",
        "Zenker’s Diverticulum",
        "Zygomatic Arch",
        "ENT",
        "Coagulation System",
        "Ablation Depth",
        "Active Electrode",
        "Active Electrode Monitoring",
        "Arcing",
        "Argon Plasma Coagulation",
        "Auto Stop Mechanism",
        "Bipolar Circuit",
        "Bipolar Forceps",
        "Bipolar Scissors",
        "Bleeding Control",
        "Blended Mode",
        "Capacitive Coupling",
        "Carbonization",
        "Coagulation Current",
        "Coagulation Efficiency",
        "Coagulation Forceps",
        "Coagulation Mode",
        "Coagulation Pathway",
        "Coagulation Seangs",
        "Coagulation Therapy",
        "Coagulum",
        "Contact Coagulation",
        "Controlled Coagulation",
        "Cooling Effect",
        "Cryotherapy",
        "Current Density",
        "Current Flow",
        "Cut Coagulate Function",
        "Cuang and Coagulating",
        "Cuang Current",
        "Cuang Mode",
        "Desiccation",
        "Diathermy",
        "Direct Coupling",
        "Electrocautery",
        "Electrode",
        "Electrode Geometry",
        "Electrode Insulation",
        "Electrode Tip",
        "Electrosurgical Burn",
        "Electrosurgical Effect",
        "Electrosurgical Generator",
        "Electrosurgical Pencil",
        "Electrosurgical Unit",
        "Electrosurgical Unit Safety",
        "Energy Delivery",
        "Energy Modulation",
        "Eschar",
        "Feedback Loop",
        "Frequency Modulation",
        "Fulguration",
        "Grounding Pad",
        "Hemostasis",
        "Hemostatic Agents",
        "Hemostatic Forceps",
        "Impedance",
        "Induced Current",
        "Intraoperative Coagulation",
        "Isolated Output",
        "Laser Ablation",
        "Laser Coagulation",
        "Lateral Heat Spread",
        "Microelectrode",
        "Microwave Coagulation",
        "Monopolar Circuit",
        "Monopolar Electrode",
        "Monopolar Scissors",
        "Non Contact Coagulation",
        "Passive Electrode",
        "Patient Return Electrode",
        "Perforation Risk",
        "Photocoagulation",
        "Plasma Beam",
        "Plasma Surgery",
        "Point Coagulation",
        "Post Coagulation Healing",
        "Power Seangs",
        "Procoagulant",
        "Radiofrequency Ablation",
        "Radiofrequency Energy",
        "Safety Margins",
        "Smoke Evacuation",
        "Thermal Coagulation",
        "Thermal Coagulator",
        "Thermal Effect",
        "Thermal Necrosis",
        "Thermal Spread",
        "Thermal Tissue Injury",
        "Thermocoagulation",
        "Tissue Ablation",
        "Tissue Adhesion",
        "Tissue Char",
        "Tissue Destruction",
        "Tissue Dissection",
        "Ultrasonic Coagulation",
        "Vaporization",
        "Vessel Sealing",
        "Voltage Regulation",
        "Wa‘age",
        "ENT",
        "Nasal Packing",
        "Absorbable Foam",
        "Absorbable Nasal Packing",
        "Absorbency",
        "Adhesion Prevention",
        "Airflow Restoration",
        "Airway Patency",
        "Anterior Epistaxis",
        "Anterior Nasal Packing",
        "Anterior Packing",
        "Anti Adhesion Barriers",
        "Antibiotic Soaked Packing",
        "Balloon Catheter",
        "Balloon Packing",
        "Balloon Tamponade",
        "Bilateral Hemorrhage",
        "Bilateral Packing",
        "Biodegradable Packing",
        "Bleeding Control",
        "Blood Clot Stabilization",
        "Coagulopathy",
        "Compression Dressing",
        "Discomfort Reduction",
        "Endoscopic Surgery",
        "Epistaxis",
        "Epistaxis Control",
        "Epistaxis Management",
        "Epistaxis Severity",
        "Foam Packing",
        "Gelatin Sponge",
        "Hemostatic Gauze",
        "Hemostatic Gel",
        "Hemostatic Sponge",
        "Hydrocolloid Packing",
        "Intranasal Pressure",
        "Intraoperative Bleeding",
        "Merocel Packing",
        "Minimal Invasiveness",
        "Mucosal Displacement",
        "Mucosal Healing",
        "Mucosal Irritation",
        "Mucosal Preservation",
        "Mucosal Protection",
        "Mucosal Reaction",
        "Mucosal Recovery",
        "Nasal Airway",
        "Nasal Cavity",
        "Nasal Congestion",
        "Nasal Debridement",
        "Nasal Fracture",
        "Nasal Hemorrhage",
        "Nasal Lavage",
        "Nasal Obstruction",
        "Nasal Packing Device",
        "Nasal Packing Insertion",
        "Nasal Packing Removal",
        "Nasal Packing Strips",
        "Nasal Plug",
        "Nasal Septum",
        "Nasal Splinting",
        "Nasal Splints",
        "Nasal Stents",
        "Nasal Tissue Support",
        "Nasal Valve Collapse",
        "Nasopharyngeal Packing",
        "Non Absorbable Nasal Packing",
        "Oxidized Cellulose",
        "Packing Absorption Rate",
        "Packing Displacement",
        "Packing Duration",
        "Packing Efficacy",
        "Packing Efficacy",
        "Packing Material",
        "Packing Material Sterilization",
        "Packing Removal",
        "Packing Retention",
        "Packing Technique",
        "Pain Management",
        "Polyvinyl Alcohol",
        "Posterior Epistaxis",
        "Posterior Nasal Packing",
        "Posterior Packing",
        "Postoperative Bleeding",
        "Postoperative Care",
        "Post Sinus Surgery",
        "Post Surgical Care",
        "Pressure Application",
        "Rhinoplasty",
        "Secondary Bleeding",
        "Septal Hematoma",
        "Septal Splints",
        "Septoplasty",
        "Sinus Surgery",
        "Sponge Packing",
        "Surgical Hemostasis",
        "Tamponade",
        "Tissue Compression",
        "Turbinates",
        "Unilateral Packing",
        "Wound Healing",
        "ENT",
        "Sinus Balloons",
        "Acute Sinusitis",
        "Anatomical Landmarks",
        "Anatomical Restoration",
        "Antral Lavage",
        "Balloon Advancement",
        "Balloon Catheter",
        "Balloon Catheter Maneuvering",
        "Balloon Catheter Navigation",
        "Balloon Catheterization",
        "Balloon Compliance",
        "Balloon Compliance Testing",
        "Balloon Deflation",
        "Balloon Deflation Technique",
        "Balloon Deployment",
        "Balloon Device Calibration",
        "Balloon Device Sterilization",
        "Balloon Dilation",
        "Balloon Dilation Therapy",
        "Balloon Endoscopy",
        "Balloon Entry",
        "Balloon Expansion",
        "Balloon Expansion Control",
        "Balloon Expansion Pressure",
        "Balloon Inflation",
        "Balloon Inflation Duration",
        "Balloon Inflation Pressure",
        "Balloon Insertion",
        "Balloon Integrity",
        "Balloon Navigation System",
        "Balloon Occlusion",
        "Balloon Placement",
        "Balloon Positioning",
        "Balloon Pressure",
        "Balloon Removal",
        "Balloon Resection",
        "Balloon Sinuplasty",
        "Balloon Technique Mastery",
        "Balloon Tip Expansion",
        "Balloon Tip Positioning",
        "Balloon Assisted Sinusotomy",
        "Balloon Based Procedure",
        "Balloon Based Sinus Surgery",
        "Ballooning Effectiveness",
        "Ballooning Force",
        "Balloon Related Complications",
        "Balloon Tipped Catheter",
        "Chronic Rhinosinusitis",
        "Chronic Sinusitis",
        "Dilation Technique",
        "Dilator Device",
        "Endoscopic Guidance",
        "Endoscopic Visualization",
        "Ethmoid Sinus",
        "Ethmoidectomy",
        "Frontal Sinus",
        "Frontalotomy",
        "Functional Endoscopic Sinus Surgery",
        "Image Guided Surgery",
        "Inflation Device",
        "Maxillary Sinus",
        "Minimally Invasive",
        "Mucociliary Clearance",
        "Mucosal Displacement",
        "Mucosal Healing",
        "Mucosal Preservation",
        "Mucosal Preservation Strategy",
        "Mucosal Swelling",
        "Ostial Dilation",
        "Ostial Obstruction",
        "Ostial Patency",
        "Ostiomeatal Complex",
        "Ostium Restoration",
        "Ostium Widening",
        "Polyp Removal",
        "Post Ballooning Care",
        "Post Dilation Recovery",
        "Post Operative Care",
        "Radiographic Guidance",
        "Recurrent Sinusitis",
        "Sinus Access",
        "Sinus Anatomy",
        "Sinus Augmentation",
        "Sinus Blockage",
        "Sinus Drainage",
        "Sinus Drainage Pathway",
        "Sinus Drainage Restoration",
        "Sinus Infection",
        "Sinus Navigation",
        "Sinus Opacification",
        "Sinus Opening",
        "Sinus Ostia",
        "Sinus Ostium",
        "Sinus Relief",
        "Sinus Septum",
        "Sinus Surgery",
        "Sinus Wall",
        "Sphenoid Sinus",
        "Sphenoidotomy",
        "Tissue Remodeling",
        "Transnasal Access",
        "ENT",
        "Airway Management Devices",
        "Advanced Airway Management",
        "Airway Clearance Therapy",
        "Airway Clearance",
        "Airway Emergency",
        "Airway Equipment",
        "Airway Evaluation",
        "Airway Exchange Catheter",
        "Airway Management Algorithm",
        "Airway Maneuvers",
        "Airway Monitoring",
        "Airway Obstruction Removal",
        "Airway Obstruction",
        "Airway Patency Compromise",
        "Airway Patency Maintenance",
        "Airway Patency",
        "Airway Pressure",
        "Airway Resistance",
        "Airway Suctioning",
        "Airway Trauma",
        "Anesthesia",
        "Apneic Oxygenation",
        "Artificial Airway",
        "Aspiration Prevention",
        "Aspiration Risk",
        "Awake Fiberoptic Intubation",
        "Bag Valve Mask",
        "Bilevel Positive Airway Pressure",
        "Bronchial Blocker",
        "Bronchoscopy",
        "Capnography",
        "Continuous Positive Airway Pressure",
        "Cricothyroid Membrane",
        "Cricothyrotomy",
        "Cuff Inflation",
        "Cuff Leak",
        "Cuff Pressure",
        "Difficult Airway",
        "Double Lumen Tube",
        "Emergency Airway",
        "Emergency Cricothyrotomy",
        "Endotracheal Tube",
        "Extubation",
        "Failed Intubation",
        "Fiberoptic Intubation",
        "High Flow Nasal Cannula",
        "Hypercapnia",
        "Hypopharyngeal Obstruction",
        "Hypoventilation",
        "Hypoxemia",
        "Intubation",
        "Laryngeal Edema",
        "Laryngeal Mask Airway",
        "Laryngeal Obstruction",
        "Laryngoscope",
        "Manual Ventilation",
        "Mechanical Ventilation",
        "Nasal Intubation",
        "Nasopharyngeal Airway",
        "Nasotracheal Intubation",
        "Oral Intubation",
        "Oropharyngeal Airway",
        "Oxygen Saturation",
        "Oxygenation",
        "Percutaneous Tracheostomy",
        "Positive Pressure Ventilation",
        "Post Intubation Care",
        "Pulmonary Aspiration",
        "Rapid Sequence Intubation",
        "Rescue Airway",
        "Retrograde Intubation",
        "Sedation",
        "Sedative Agents",
        "Stomal Care",
        "Subgloac Stenosis",
        "Subgloac Suction",
        "Suction Catheter",
        "Supragloac Airway",
        "Supragloac Devices",
        "Surgical Airway Access",
        "Surgical Airway",
        "Tracheal Decannulation",
        "Tracheal Intubation",
        "Tracheal Stenosis",
        "Tracheal Stoma",
        "Tracheal Tube",
        "Tracheostomy Tube Change",
        "Tracheostomy",
        "Transtracheal Jet Ventilation",
        "Tube Displacement",
        "Tube Malposition",
        "Tube Placement Confirmation",
        "Tube Securement",
        "Upper Airway Obstruction",
        "Ventilation",
        "Ventilator Seangs",
        "Ventilator Weaning",
        "Ventilator Associated Event",
        "Ventilator Associated Pneumonia",
        "Video Laryngoscopy",
        "Trauma",
        "Trauma",
        "Generic",
        "AllograP",
        "Anatomical Plate",
        "Antegrade",
        "Anti Glide Plate",
        "AutograP",
        "Bicortical Screw",
        "Bone Awl",
        "Bone Cure‘e",
        "Bone Cu‘er",
        "Bone Drill",
        "Bone GraP",
        "Bone Healing",
        "Bone Holding Forceps",
        "Bone Hook",
        "Bone Nibbler",
        "Bone Plate",
        "Bone Rasp",
        "Bone Saw",
        "Bone Substitute",
        "Bone Tap",
        "Bridging Plate",
        "Bu‘ress Plate",
        "Callus Formation",
        "Cancellous Screw",
        "Cannulated Screw",
        "Chisel",
        "Closed Fracture",
        "Combination Screw",
        "Comminuted Fracture",
        "Compression Screw",
        "Cortical Screw",
        "Depth Gauge",
        "Diaphysis",
        "Distal Femoral Nail",
        "Distal",
        "Drill Bit",
        "Drill Guide",
        "Dynamic Compression Plate",
        "Dynamic Hip Screw",
        "Epiphysis",
        "Extra Articular Fracture",
        "Fracture",
        "Gamma Nail",
        "Greater Trochanter Fracture",
        "Guide Pin",
        "Guide Wire",
        "Implant Removal",
        "Interfragmentary Screw",
        "Interlocking Nail",
        "Intertrochanteric Nail",
        "Intra Articular Fracture",
        "Intramedullary Fixation",
        "Intramedullary Nail",
        "Intramedullary Reamer",
        "K Wire Kirschner Wire",
        "Lag Screw",
        "Screw designed to compress and stabilize fractures",
        "Lagging Technique",
        "Limited Contact Dynamic Compression Plate",
        "Locking Plate",
        "Locking Screw",
        "Mallet",
        "Malunion",
        "Medullary Canal",
        "Metaphysis",
        "Monoaxial Screw",
        "Nail Extractor",
        "Nail Inserter",
        "Neutralization Plate",
        "Non Locking Screw",
        "Nonunion",
        "Oblique Fracture",
        "Open Fracture",
        "Open Reduction Internal Fixation",
        "Osteoporosis",
        "Osteosynthesis",
        "Osteotome",
        "PEEK Plate",
        "Perioperative Complications",
        "Periosteal Elevator",
        "Plate Bender",
        "Plate Cu‘er",
        "Polyaxial Screw",
        "Postoperative Care",
        "Proximal",
        "Proximal Femoral Nail",
        "Rasp",
        "Reconstruction Plate",
        "Reduction Clamp",
        "Rehabilitation",
        "Retrograde",
        "Rongeur",
        "Screw Extractor",
        "Screw Inserter",
        "Screwdriver",
        "Segmental Fracture",
        "Self Tapping Screw",
        "SoP Tissue Management",
        "Spiral Fracture",
        "Stainless Steel Plate",
        "Sterilization",
        "Subtrochanteric Nail",
        "Supracondylar Nail",
        "Tap",
        "Tension Band Plate",
        "Tension Band Wiring",
        "Titanium Plate",
        "Transverse Fracture",
        "Unicortical Screw",
        "Variable Angle Plates",
        "Weight Bearing",
        "Wound Closure",
      ];
     

// ✅ API integration
async function makeTextToSpeechCall(text) {
  try {
    const response = await fetch("https://api.sarvam.ai/text-to-speech", {
      method: "POST",
      headers: {
        "api-subscription-key": "sk_ydk1b5db_Ut4Gw4gQW8b4ZN4chcsMvNQT",
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        text: text,
        target_language_code: "en-IN",
        speaker: "anushka",
        pitch: 0,
        loudness: 1,
        pace: 0.9,
        speech_sample_rate: "24000",
        model: "bulbul:v2",
      }),
    });

    const body = await response.json();
    if (body.audios && body.audios.length > 0) {
      const audio = new Audio(`data:audio/mp3;base64,${body.audios[0]}`);
      await audio.play();
    } else {
      console.error("No audio received for:", text);
    }
  } catch (err) {
    console.error("TTS Error for", text, ":", err);
  }
}

// ✅ Clean text content
function cleanText(text) {
  return text.replace(/&#160;/g, " ").replace(/\s+/g, " ").trim();
}

// ✅ Button creation
function createTTSButton(text) {
  const button = document.createElement("button");
  button.innerHTML = `
    <svg xmlns="http://www.w3.org/2000/svg" fill="none"
         viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor"
         width="28" height="28"> <!-- Increased size -->
      <path stroke-linecap="round" stroke-linejoin="round"
            d="M19.114 5.636a9 9 0 0 1 0 12.728M16.463
               8.288a5.25 5.25 0 0 1 0 7.424M6.75 8.25l4.72-4.72a.75.75
               0 0 1 1.28.53v15.88a.75.75 0 0
               1-1.28.53l-4.72-4.72H4.51c-.88 0-1.704-.507-1.938-1.354A9.009
               9.009 0 0 1 2.25 12c0-.83.112-1.633.322-2.396C2.806
               8.756 3.63 8.25 4.51 8.25H6.75Z" />
    </svg>`;
  button.setAttribute("title", `Speak: ${text}`);
  button.dataset.text = text;
  button.classList.add("tts-button");

  Object.assign(button.style, {
    marginLeft: "5px",
    background: "transparent",
    border: "0",
    cursor: "pointer",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    width: "12px",
    height: "12px",
    padding: "1px",
    color: "black",
  });

  button.addEventListener("click", async (e) => {
    e.preventDefault();
    button.disabled = true;
    button.style.opacity = "0.5";
    await makeTextToSpeechCall(text);
    button.disabled = false;
    button.style.opacity = "1";
  });

  return button;
}


// ✅ Insert button next to an element
function addInlineTTSButton(element, text) {
  if (processedElements.has(element)) return;
  processedElements.add(element);
  const btn = createTTSButton(text);
  element.appendChild(btn);
}

// ✅ Search for target phrases inside <h3> tags
function injectSpeakButtonsForBoldTerms(container = document) {
  const boldElements = Array.from(container.querySelectorAll("h2"));
  boldElements.forEach((el) => {
    if (processedElements.has(el)) return;
    const text = cleanText(el.textContent);
    if (phrases.some((p) => text.includes(p))) {
      addInlineTTSButton(el, text);
    }
  });
}

// ✅ Init all logic
function initializeTTS() {
  setTimeout(() => {
    injectSpeakButtonsForBoldTerms();
  }, 200);
}

// ✅ DOM Ready Hook
if (document.readyState === "loading") {
  document.addEventListener("DOMContentLoaded", initializeTTS);
} else {
  initializeTTS();
}
